spring:
  datasource:
    url: jdbc:h2:mem:products-microservice;DATABASE_TO_UPPER=false
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  flyway:
    clean-disabled: false
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
